force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Monthly_Rent__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rent__c</fullName>
    <label>Monthly Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Pets__c.field-meta.xml
<CustomField>
    <fullName>Pets__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks if the tenant will have Pets in the property</description>
    <inlineHelpText>Check it if you will have Pets with you in the property. Maximum 3 Pets allowed</inlineHelpText>
    <label>Pets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
                <default>true</default>
                <label>Apartment</label>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Townhomes</fullName>
            </value>
            <value>
                <fullName>Yurt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Smoking__c.field-meta.xml
<CustomField>
    <fullName>Smoking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Smoker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NotificationBatchTest.cls
@IsTest
private class NotificationBatchTest {
    @IsTest
    public static void sendEmailTest() {
        Property__c testProp = new Property__c(Smoking__c = true, Pets__c = true, Monthly_Rent__c = 1000, Property_Type__c = 'Apartment', End_date__c = System.today().addDays(25));
        insert testProp;

        Test.startTest();
        NotificationBatch batch = new NotificationBatch();
        Database.executeBatch(batch, 200);
        Test.stopTest();
    }
}