force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
                <default>true</default>
                <label>Apartment</label>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Townhomes</fullName>
            </value>
            <value>
                <fullName>Yurt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChartControllerTest.cls
@IsTest(SeeAllData=false)
public with sharing class ChartControllerTest {
    @isTest
    static void ChartControllerPositiveTest() {

        //given
        List <Property__c> propertytest = new List<Property__c> ();
        //Map<String, Integer> propertytest = new Map<String, Integer>();
        propertytest.add(new Property__c(Property_Type__c='Apartment'));
        propertytest.add(new Property__c(Property_Type__c='House'));
        propertytest.add(new Property__c(Property_Type__c='Penthouse'));
        propertytest.add(new Property__c(Property_Type__c='Townhomes'));
        propertytest.add(new Property__c(Property_Type__c='Yurt'));

        //when
        Test.startTest();
        insert propertytest;
        Test.stopTest();

        //Then
        Integer expectedsize = propertytest.size();
        Integer actualsize = ChartController.getStatistics().size();

        System.assertEquals(expectedsize, actualsize);

    }
}