force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Rented__c.field-meta.xml
<CustomField>
    <fullName>Is_Rented__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rented</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties (Tenant)</relationshipLabel>
    <relationshipName>Properties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/batchables/PropertyLeaveBatch.cls
/**
 * Batch class to check for finished rent in properties and deleting Contacts
 * @author MartinCapek
 */
public class PropertyLeaveBatch implements Database.Batchable<SObject>, Schedulable {
    public static void execute(SchedulableContext ctx) {
        PropertyLeaveBatch batch = new PropertyLeaveBatch();
        Database.executeBatch(batch, 200);
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator ('SELECT Id,End_date__c,tenant__c FROM property__c WHERE End_date__c <= today AND IS_rented__C = true');
    }

    public void execute(Database.BatchableContext BC, List<Property__c> propList) {
        Set <Id> contIds = new Set <Id>();

        // process each batch of records default size 200
        for (Property__c prop : propList) {
            // Update the Account Name 
            prop.Is_Rented__c = false;
            contIds.add(prop.Tenant__c);
        }

        update propList;

        List <Contact> cList = [SELECT Id FROM Contact WHERE Id IN :contIds];
        delete cList;
    }

    public void finish(Database.BatchableContext BC) {
    }
}
      
             
          
         
        