force-app/main/default/objects/Contact/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Income__c.field-meta.xml
<CustomField>
    <fullName>Income__c</fullName>
    <label>Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Rented__c.field-meta.xml
<CustomField>
    <fullName>Is_Rented__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rented</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties (Tenant)</relationshipLabel>
    <relationshipName>Properties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PropertyLeaveBatchTest.cls
@IsTest(SeeAllData=false)

private class PropertyLeaveBatchTest{
    
    @IsTest
    static void EndToday() {
        //given
        
        contact con1  =new contact (Credit_Score__c=1000,income__c=1000,email='test@test.gmail.com',lastname='test',birthdate=Date.newInstance(2000, 1, 1), Occupation__c='manager');
        contact con2  =new contact (Credit_Score__c=1000,income__c=1000,email='test2@test2.gmail.com',lastname='test2',birthdate=Date.newInstance(2001, 1, 1), Occupation__c='manager');

        property__c prop1= new property__c (Is_Rented__c=true, End_date__c = system.today(), tenant__c = con1.Id);
        property__c prop2= new property__c (Is_Rented__c=true, End_date__c = system.today().addDays(+1), tenant__c = con2.id);
        
        insert con1;
        insert prop1;
        insert con2;
        insert prop2;
        prop1.tenant__C=con1.Id;
        prop2.tenant__C=con2.Id;
        update prop1;
        update prop2;
         

        //when
        Test.startTest();
        
        PropertyLeaveBatch bc = new PropertyLeaveBatch();
        database.executeBatch(bc);
        Test.stopTest();


        //then
        
      	property__c testprop1= [SELECT id,is_rented__C FROM property__c WHERE id=:prop1.id limit  1 ];
        property__c testprop2= [SELECT id,is_rented__C,tenant__c FROM property__c WHERE id=:prop2.id limit  1 ];
        integer count = [SELECT COUNT() FROM Contact WHERE Id = :con1.id];
        integer count2 =[SELECT COUNT() FROM Contact WHERE Id = :con2.id];
        

        System.assertEquals(count,0);
        System.assertEquals(count2,1);

        
        System.assertEquals(testprop1.is_rented__c,false);
        System.assertEquals(testprop2.is_rented__c,true);
  
    }
}