force-app/main/default/objects/Contact/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Tenant.recordType-meta.xml
<RecordType>
    <fullName>Tenant</fullName>
    <active>true</active>
    <label>Tenant</label>
</RecordType>

force-app/main/default/classes/ContactServiceTest.cls
@IsTest(SeeAllData=false)
private class ContactServiceTest {
    
    @IsTest
    static void validateTenantWithBadInputsTest() {
        //given
        Contact tooYoung = new Contact(Credit_Score__c = 630, Occupation__c = 'Software Engineer', Birthdate = Date.newInstance(2010, 2, 17));
        Contact unemployeedTenant = new Contact(Credit_Score__c = 630, Occupation__c = 'Student', Birthdate = Date.newInstance(1975, 2, 17));
        Contact lowCreditScore = new Contact(Credit_Score__c = 628,  Occupation__c = 'Software Engineer', Birthdate = Date.newInstance(1975, 2, 17));

        //when
        Test.startTest();
        Database.SaveResult resultTooYounng = Database.insert(tooYoung, false);
        Database.SaveResult resultUnemployeedTenant = Database.insert(unemployeedTenant, false);
        Database.SaveResult resultLowCreditScore = Database.insert(lowCreditScore, false);        
        Test.stopTest();

        //then
        System.assertEquals(resultTooYounng.getErrors()[0].getMessage(), 'This tenant is too young to deal with.');
        System.assertEquals(resultUnemployeedTenant.getErrors()[0].getMessage(), 'This tenant is Student or unemployed.');
        System.assertEquals(resultLowCreditScore.getErrors()[0].getMessage(), 'This tenant has too low credit score. It should be more than 629.');
    }  
    
    @IsTest
    static void validateTenantWithGoodInputsTest() {
        //given
        Contact testTenant = new Contact(LastName = 'test', Credit_Score__c = 630, Occupation__c = 'Software Engineer',  Birthdate = Date.newInstance(1975, 2, 17));

        //when
        Test.startTest();
        Database.SaveResult result = Database.insert(testTenant, false);       
        Test.stopTest();
        
        //then
        System.assert(result.isSuccess());
    }  
}