force-app/main/default/objects/Contact/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Tenant.recordType-meta.xml
<RecordType>
    <fullName>Tenant</fullName>
    <active>true</active>
    <label>Tenant</label>
</RecordType>

force-app/main/default/classes/ContactService.cls
public with sharing class ContactService {

    /**
     * Method validates tenant before insert to Contact.
     * 
     * @param newList new inserted contacts
     * @author belekomurzakov
     */
    public static void validateTenant(List<Contact> newList) {
        for(Contact contact : newList) {
            if (contact.Credit_Score__c == null ||contact.Credit_Score__c < 629) {
                contact.addError('This tenant has too low credit score. It should be more than 629.');
            }
            if (String.isEmpty(contact.Occupation__c) || contact.Occupation__c == 'Student') {
                contact.addError('This tenant is Student or unemployed.');
            }

            if (contact.Birthdate == null || Date.today().year() - contact.Birthdate.year() < 18) {
                contact.addError('This tenant is too young to deal with.');
            }            
        }
    }
}