force-app/main/default/objects/Contact/fields/Credit_Score__c.field-meta.xml
<CustomField>
    <fullName>Credit_Score__c</fullName>
    <label>Credit Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payments__c/Payments__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payments__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Tenants__c.field-meta.xml
<CustomField>
    <fullName>Tenants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Annual_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Annual_Expenses__c</fullName>
    <label>Annual Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Annual_Rent__c.field-meta.xml
<CustomField>
    <fullName>Annual_Rent__c</fullName>
    <label>Annual Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Initial_Investment__c.field-meta.xml
<CustomField>
    <fullName>Initial_Investment__c</fullName>
    <label>Initial Investment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Paid__c.field-meta.xml
<CustomField>
    <fullName>Is_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Rented__c.field-meta.xml
<CustomField>
    <fullName>Is_Rented__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rented</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Monthly_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Insurance__c</fullName>
    <label>Monthly Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Monthly_Profit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Profit__c</fullName>
    <label>Monthly Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Monthly_Rent__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rent__c</fullName>
    <label>Monthly Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Monthly_Rental_Expense__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rental_Expense__c</fullName>
    <label>Monthly Rental Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Monthly_Utilities__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Utilities__c</fullName>
    <label>Monthly Utilities</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Pets__c.field-meta.xml
<CustomField>
    <fullName>Pets__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks if the tenant will have Pets in the property</description>
    <inlineHelpText>Check it if you will have Pets with you in the property. Maximum 3 Pets allowed</inlineHelpText>
    <label>Pets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apartment</fullName>
                <default>true</default>
                <label>Apartment</label>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>Townhomes</fullName>
            </value>
            <value>
                <fullName>Yurt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Smoking__c.field-meta.xml
<CustomField>
    <fullName>Smoking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Smoker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties (Tenant)</relationshipLabel>
    <relationshipName>Properties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Utility_Included__c.field-meta.xml
<CustomField>
    <fullName>Utility_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Utility Included</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PropertyServiceTest.cls
@IsTest(SeeAllData=false)

public with sharing class PropertyServiceTest {
    @isTest
    static void PropertyServicePositiveInsertTest() {


        //given
        Property__c testProp = new Property__c(Smoking__c=true, Pets__c=true,Monthly_rent__c=1000,Property_type__c='Apartment');
       

        //when
        test.startTest();
        insert testProp;
        test.stopTest();

        //then
        Property__c result = [select Monthly_rent__c from Property__c where id =:testProp.id];
        System.assertEquals(1200, result.Monthly_Rent__c,'Result value is '+ result.Monthly_Rent__c);
    }

    @isTest
    static void PropertyServicePositiveUpdateTest() {


        //given
        Property__c testProp = new Property__c(Smoking__c=false, Pets__c=false,Monthly_rent__c=1000,Property_type__c='Apartment');
        insert testProp;
        testProp.Smoking__c=true;
        testProp.Pets__c=true;
        //when
        test.startTest();
        update testProp;
        test.stopTest();

        //then
        Property__c result = [select Monthly_rent__c from Property__c where id =:testProp.id];
        System.assertEquals(1200, result.Monthly_Rent__c,'Result value is '+ result.Monthly_Rent__c);
    }
}


private class PropertyServiceTest{
    
    @IsTest
    static void MonthlyRentCalculatorTest() {
        //given 
        property__c utIncluded= new property__c (Monthly_rent__c = 50, Monthly_insurance__c = 10, monthly_rental_Expense__c = 10,
                                                Monthly_utilities__c = 10, Is_Rented__c=true, Utility_included__c = true , initial_investment__C = 10);
        property__c utNotIncluded= new property__c (Monthly_rent__c = 50, Monthly_insurance__c = 10, monthly_rental_Expense__c = 10,
                                                Monthly_utilities__c = 10, Is_Rented__c = true, Utility_included__c = false, initial_investment__C = 10);
        property__c notRented= new property__c (Monthly_rent__c = 50, Monthly_insurance__c = 10, monthly_rental_Expense__c = 10,
                                                Monthly_utilities__c=10, Is_Rented__c = false, Utility_included__c=true);


        //when
        Test.startTest();
        insert UtIncluded;
        insert utNotIncluded;
        insert notRented; 
        Test.stopTest();


        //then
        property__c testUtIncluded= [SELECT id, Monthly_profit__c,annual_Expenses__c,annual_rent__c,initial_investment__C,roi__c FROM property__c WHERE ID=:utIncluded.id ];
        property__c testutNotIncluded= [SELECT id, Monthly_profit__c,annual_Expenses__c,annual_rent__c,initial_investment__C,roi__c FROM property__c WHERE ID=:utNotIncluded.id ];
        property__c testnotRented= [SELECT id, Monthly_profit__c FROM property__c WHERE ID=: notRented.id ];
        
        
        System.assertEquals(testUtIncluded.Monthly_profit__c,20);
        System.assertEquals(testutIncluded.annual_Expenses__c,360);
        System.assertEquals(testutNotIncluded.Monthly_profit__c,30);
        System.assertEquals(testutNotIncluded.annual_Expenses__c,240);
        System.assertEquals(testnotRented.Monthly_profit__c,null);
        System.assertEquals(testutIncluded.annual_rent__c,600);
        System.assertEquals(testutIncluded.roi__c,2400);
        System.assertEquals(testutNotIncluded.roi__c,3600);


    }

    @IsTest
    static void checkForBillsEachMonthTest(){
        //given
        Contact newContact = new Contact(Phone = '000', Credit_Score__c = 700,  Occupation__c = 'Software Engineer', Birthdate = Date.newInstance(1975, 2, 17), Email='test@gmail.com', LastName='Zhaniev');
        insert newContact;
        Payments__c newPayment = new Payments__c(Date__c= Date.newInstance(2022, 7, 17), Tenants__c=newContact.Id);
        insert newPayment;
        Property__c newProperty = new Property__c(Is_Rented__c=true, Is_Paid__c=false, Tenant__c=newContact.Id);

        
        //when
        Test.startTest();
        insert newProperty;
        Test.stopTest();

  
    }
}