force-app/main/default/objects/Contact/recordTypes/Tenant.recordType-meta.xml
<RecordType>
    <fullName>Tenant</fullName>
    <active>true</active>
    <label>Tenant</label>
</RecordType>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Is_Rented__c.field-meta.xml
<CustomField>
    <fullName>Is_Rented__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rented</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties (Tenant)</relationshipLabel>
    <relationshipName>Properties2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PropertyLeaveBatch.cls
 /**
     * Batch method to check for finished rent in properties and deleting contacts
     * 
     * 
     * @author MartinCapek
     */


    public class PropertyLeaveBatch implements Database.Batchable<sObject>,schedulable{ 
        public static void execute (schedulablecontext ctx){} 
        
        //Select Property ID and Tenant Id from property, where end date is today or less and is still rented
        public Database.QueryLocator start(Database.BatchableContext BC) {
            return Database.getQueryLocator ('SELECT Id,End_date__c,tenant__c FROM property__c WHERE End_date__c <= today AND IS_rented__C = true');
        } 

        
        public void execute(Database.BatchableContext BC, List<property__C> propList) {
            Set <id> contIds = new set <id>();
            // process each batch of records default size 200
            for(property__c prop : propList) {        
                // Update the Account Name 
                prop.IS_rented__C = false;
                contIds.add(prop.tenant__c);
                
            }   
            update proplist;    
            
            list <contact> clist =[SELECT Id FROM contact WHERE id IN :contIds ];
            Delete clist;  
        } 
       public void finish(Database.BatchableContext BC) {
        
        }
    }
      
             
          
         
        